"""
test_generator.py — Generate pytest test cases for identified missing scenarios.

Two strategies:
1. AI generation via Google Gemini gemini-3.8-flash (preferred)
2. Template-based fallback (always available)
"""

import os
import re
from typing import List

from dotenv import load_dotenv

load_dotenv(dotenv_path=os.path.join(os.path.dirname(__file__), '..', '.env'))

_GEMINI_AVAILABLE = False
_client = None

try:
    from google import genai
    api_key = os.getenv("GEMINI_API_KEY", "")
    if api_key and api_key not in ("your-gemini-api-key-here", "your-openai-api-key-here"):
        _client = genai.Client(api_key=api_key)
        _GEMINI_AVAILABLE = True
except Exception:
    pass


def count_tests_in_code(test_code: str) -> int:
    """Count the number of def test_ functions in a code string."""
    return len(re.findall(r'^\s*def test_', test_code, re.MULTILINE))


def _scenario_to_func_name(scenario: str) -> str:
    """Convert a scenario description to a valid Python function name."""
    name = scenario.lower()
    name = re.sub(r'[^a-z0-9_\s]', '', name)
    name = re.sub(r'\s+', '_', name.strip())
    name = re.sub(r'_+', '_', name)
    return "test_" + name[:60]


def _build_generation_prompt(code: str, tests: str, missing_tests: List[dict], edge_cases: List[dict]) -> str:
    """Build the prompt for test generation."""
    missing_list = "\n".join(
        f"- [{m.get('risk','?').upper()}] {m.get('scenario','?')}: {m.get('reason','')}"
        for m in missing_tests
    )
    edge_list = "\n".join(
        f"- [{e.get('type','?')}] {e.get('description','?')}"
        for e in edge_cases
    )

    prompt = f"""You are a Python testing expert. Write complete, runnable pytest test cases.

## Source Code to Test
```python
{code.strip()}
```

## Existing Tests (do NOT duplicate these)
```python
{tests.strip() if tests.strip() else "# None"}
```

## Missing Test Scenarios to Cover
{missing_list if missing_list else "No specific scenarios — generate comprehensive tests."}

## Edge Cases to Cover
{edge_list if edge_list else "No specific edge cases."}

## Requirements
1. Write complete pytest functions (def test_...:)
2. Each test must have at least one assert statement
3. Add a docstring to each test explaining what it verifies
4. Add a comment above each test explaining why it's important
5. Import the function(s) being tested at the top
6. Start the file with: # Generated by TestGuard AI
7. The tests must be syntactically valid Python
8. Use realistic test values based on the actual code logic

Return ONLY valid Python code. No markdown fences, no explanation outside the code.
"""
    return prompt


def _build_explanation(missing_tests: List[dict], edge_cases: List[dict], test_count_before: int, test_count_after: int) -> str:
    """Build a human-readable explanation of what was generated."""
    high = sum(1 for m in missing_tests if m.get("risk") == "high")
    medium = sum(1 for m in missing_tests if m.get("risk") == "medium")
    ec_count = len(edge_cases)

    parts = []
    if high:
        parts.append(f"{high} high-risk untested branch(es)")
    if medium:
        parts.append(f"{medium} medium-risk scenario(s)")
    if ec_count:
        parts.append(f"{ec_count} edge case(s)")

    coverage_note = (
        f"Expanded from {test_count_before} existing test(s) to {test_count_after} recommended test(s). "
        if test_count_after > test_count_before
        else f"Generated {test_count_after} recommended test(s). "
    )

    return (
        coverage_note +
        ("Covering: " + ", ".join(parts) + ". " if parts else "") +
        "These are AI-generated recommendations — review and adapt them to your project before use."
    )


def generate_fallback(
    code: str,
    missing_tests: List[dict],
    edge_cases: List[dict],
    test_count_before: int,
) -> dict:
    """
    Template-based test generation — works without AI.
    Produces skeleton tests with explanatory comments.
    """
    lines = [
        "# Generated by TestGuard AI — Template-based recommendations",
        "# Review and adapt these tests before running them in your project.",
        "# Replace 'your_module' with the actual module name.",
        "",
        "import pytest",
        "# from your_module import <function_name>",
        "",
        "",
    ]

    all_scenarios = list(missing_tests) + [
        {"scenario": e["description"], "reason": e.get("description", ""), "risk": "low", "function_name": e.get("function_name", "")}
        for e in edge_cases
    ]

    if not all_scenarios:
        lines.append("# No missing scenarios detected — your tests may already be comprehensive.")
        lines.append("def test_placeholder():")
        lines.append('    """Placeholder — no specific gaps detected."""')
        lines.append("    pass")
    else:
        for scenario in all_scenarios:
            func_name = _scenario_to_func_name(scenario.get("scenario", "scenario"))
            risk = scenario.get("risk", "low").upper()
            reason = scenario.get("reason", scenario.get("scenario", ""))
            source_func = scenario.get("function_name", "")

            lines.append(f"# [{risk}] {scenario.get('scenario', '')}")
            lines.append(f"def {func_name}():")
            lines.append(f'    """')
            lines.append(f'    TODO: {reason}')
            if source_func:
                lines.append(f'    Tests: {source_func}()')
            lines.append(f'    """')
            lines.append(f"    # TODO: Set up test inputs")
            lines.append(f"    # result = {source_func}(...)  # call the function")
            lines.append(f"    # assert result == expected_value")
            lines.append(f"    pass")
            lines.append("")

    generated_code = "\n".join(lines)
    test_count_after = count_tests_in_code(generated_code)

    return {
        "generated_tests": generated_code,
        "explanation": _build_explanation(missing_tests, edge_cases, test_count_before, test_count_after),
        "test_count_before": test_count_before,
        "test_count_after": test_count_after,
    }


def generate_with_ai(
    code: str,
    tests: str,
    missing_tests: List[dict],
    edge_cases: List[dict],
    test_count_before: int,
) -> dict:
    """
    AI-powered test generation using Google Gemini.
    Falls back to template generation if AI is unavailable.
    """
    if not _GEMINI_AVAILABLE or _client is None:
        return generate_fallback(code, missing_tests, edge_cases, test_count_before)

    try:
        prompt = _build_generation_prompt(code, tests, missing_tests, edge_cases)

        response = _client.models.generate_content(
            model="gemini-flash-lite-latest",
            contents=prompt,
            config={
                "temperature": 0.2,
                "max_output_tokens": 2000,
            },
        )

        generated_code = response.text.strip()

        # Strip markdown code fences if the model added them
        generated_code = re.sub(r'^```python\s*', '', generated_code, flags=re.MULTILINE)
        generated_code = re.sub(r'^```\s*$', '', generated_code, flags=re.MULTILINE)
        generated_code = generated_code.strip()

        test_count_after = count_tests_in_code(generated_code)

        return {
            "generated_tests": generated_code,
            "explanation": _build_explanation(missing_tests, edge_cases, test_count_before, test_count_after),
            "test_count_before": test_count_before,
            "test_count_after": test_count_after,
        }

    except Exception as e:
        # Fall back to template generation on any error
        result = generate_fallback(code, missing_tests, edge_cases, test_count_before)
        result["explanation"] = (
            f"AI generation failed ({type(e).__name__}). Showing template-based recommendations. " +
            result["explanation"]
        )
        return result
